return error

diff --git a/.github/workflows/thirteen-workflow.yml b/.github/workflows/thirteen-workflow.yml
--- a/.github/workflows/thirteen-workflow.yml
+++ b/.github/workflows/thirteen-workflow.yml
@@ -6,7 +6,9 @@ jobs:
   job:
     runs-on: ubuntu-latest
     steps:
-      
+      - name: Failure step
+        id: error-step
+        run: exit 1
       - name: Runs On Cancelled
         if: ${{ cancelled() }} 
         run: echo "Runs On Cancelled"
@@ -17,7 +19,7 @@ jobs:
         if: ${{ always() }} 
         run: echo "Runs anyway"
       - name: Runs On Failure
-        if: ${{ failure() }} 
+        if: ${{ failure() && steps.error-step.conclusion == 'failure'}} 
         run: echo "Runs On Failure"
   second-job:
     runs-on: ubuntu-latest
